name: Build Docker Image

on:
  release:
    types: [published]

jobs:
  setup-build:
    name: SETUP, BUILD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Package Name
        run: echo 'PACKAGE='$(echo $GITHUB_REF_NAME | cut -d "@" -f 1) >> $GITHUB_ENV

      - name: Set Package Version
        run: echo "VERSION="$(echo $GITHUB_REF_NAME) | cut -d "@" -f 2) >> $GITHUB_ENV

      - name: Build
        run: |-
          cd ./packages/${{env.PACKAGE}}
          docker build --tag "{{env.PACKAGE}}:${{env.VERSION}}" .
